apiVersion: v1
kind: Service
metadata:
{{- if ( default false .Values.useCanary ) }}
  name: {{ (print .Values.service "-stable") | lower | quote }}
{{- else }}
  name: {{ .Values.service | lower | quote }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    version: {{ .Values.version | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
{{- range .Values.ports }}
    - name: {{ .name | quote }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
{{- end }}
  selector:
    app: {{ .Values.service | lower | quote }}
{{- if ( default false .Values.useCanary ) }}
--
apiVersion: v1
kind: Service
metadata:
  name: {{ (print .Values.service "-canary") | lower | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    version: {{ .Values.version | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
{{- range .Values.ports }}
    - name: {{ .name | quote }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
{{- end }}
  selector:
    app: {{ .Values.service | lower | quote }}
{{- end }}